### ISSUE TITLE
Sensor return expecting float result

### ISSUE THREAD

**Issue by Ecklypse** [paulchartres/hass-tiko#1]
Hi Paul, 
I had to correct some bits on Tiko Yaml. Indeed, logs returned at beginning sur failure due to sensor expecting a float. 
As example, i corrected this way with | Float(0):
action:
        - service: climate.set_temperature
          target:
            entity_id: climate.louise
          data:
            temperature: "{{states('sensor.louise_temperature_target')|float (0)}}"

Issues then disappeared. 
regards, 
Ludovic

**Comment by paulchartres** [comment]
Fixed in the latest version, thanks!
