### ISSUE TITLE
Sensor Unique ID

### ISSUE THREAD

**Issue by Ecklypse** [paulchartres/hass-tiko#2]
HI Paul,

I added in the tiko.yaml unique id's.
Indeed this allows to better handle them with lovelace.
As example: 
sensors:
        parents_humidity:
          friendly_name: Parents humidity
          unique_id: parents_humidity
          value_template: "{{ state_attr('sensor.tiko_settings', 'parents_dry')}}"
          unit_of_measurement: "%"
          device_class: humidity

I think it could make sense indeed to add that to all of those generated. What do you think?

**Comment by paulchartres** [comment]
Fixed in the latest version, thanks for the suggestion!
