### ISSUE TITLE
IMPROVEMENT PROPOSAL:

### ISSUE THREAD

**Issue by Ecklypse** [paulchartres/hass-tiko#4]
Hello Paul,

Hope you are doing well?
Paul as improvements for the road map:
1- it would be good to be able to collect the energy consumption per heater so it can be added into the energy dashboard.
use case: i am monitoring my global real time consumption with a Linky Lixee. adding the heaters would allow me to know how much the heating impacts the consumption overall. On top of this, it would allow me to check if one is consuming much more than any other and to find proper solution to remediate. 

2 - A native dashboard proposal would be nice as well with thermostats, switches and consumption potentially 

Thank you.

Note i posted it here as an issue, as i am not yet sure if there is a dedicated place for similar request?

**Comment by paulchartres** [comment]
I created two issues to track these improvements:
https://github.com/paulchartres/hass-tiko/issues/5 and https://github.com/paulchartres/hass-tiko/issues/6
This is the right place for such suggestions, no worries!
